<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Cek_harga extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        
        $this->load->model('Tbl_harga_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $data = array(
            'merk'      => $this->Tbl_harga_model->get_all_merk(),
            'tipe'      => $this->Tbl_harga_model->get_all_tipe(),
        );

        $this->load->view('cek_harga/index.php', $data);
    }

    public function merk($id)
    {
        $data = array(
            'tipe'      => $this->Tbl_harga_model->get_all_tipe_by_merk($id),
        );

        $this->load->view('cek_harga/merk.php', $data);
    }

    public function detail_tipe($id) {
        $data = array(
            'tipe'        => $this->Tbl_harga_model->get_all_tipe_by_id($id),
            'memori'      => $this->Tbl_harga_model->get_all_memori_ada($id),
            'kualifikasi' => $this->Tbl_harga_model->get_all_kualifikasi(),
            'kondisi'     => $this->Tbl_harga_model->get_all_kondisi(),
            
        );
        $this->load->view('cek_harga/detail_tipe.php', $data);
    }

    public function detail_harga() {

        $id = $this->input->get('id_tipe');

        $data = array(
            'record'        => $this->Tbl_harga_model->get_detail_harga(),
            'tipe'          => $this->Tbl_harga_model->get_all_tipe_by_id($id),
            'memori'        => $this->Tbl_harga_model->get_all_memori_ada($id),
            'kualifikasi'   => $this->Tbl_harga_model->get_all_kualifikasi(),
            'kondisi'       => $this->Tbl_harga_model->get_all_kondisi(),
        );
        $this->load->view('cek_harga/detail_harga.php', $data);
    }

    public function tukar_tambah() {

        $data = array(
            'tipe'      => $this->Tbl_harga_model->get_all_tt(),
            'tipe_baru' => $this->Tbl_harga_model->get_all_baru(),
        );
        $this->load->view('cek_harga/tukar_tambah.php', $data);
    }

    public function tt_action() {
    
        $data = array(
            'tipe'      => $this->Tbl_harga_model->get_all_tt(),
            'tipe_baru' => $this->Tbl_harga_model->get_all_baru(),
            'id_tipe'   => $this->input->get('id_tipe'),
            'id_baru'   => $this->input->get('id_baru'),
            
        );
        $this->load->view('cek_harga/hasil_tukar_tambah.php', $data);
    }


}

/* End of file Cek_harga.php */
/* Location: ./application/controllers/Tbl_harga.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-04-24 07:51:32 */
/* http://harviacode.com */