<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_tipe_model_it extends CI_Model
{

    public $table = 'tbl_tipe';
    public $id = 'id_tipe';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('tbl_merk', 'tbl_merk.id_merk = tbl_tipe.id_merk');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    
    function get_all_merk()
    {
        $this->db->order_by('id_merk', 'ASC');
        return $this->db->get('tbl_merk')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->join('tbl_merk', 'tbl_merk.id_merk = tbl_tipe.id_merk');
        $this->db->like('id_tipe', $q);
        $this->db->or_like('nama_tipe', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('tbl_merk', 'tbl_merk.id_merk = tbl_tipe.id_merk');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_tipe', $q);
        $this->db->or_like('nama_tipe', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_tipe_model.php */
/* Location: ./application/models/Tbl_tipe_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-04-24 07:23:33 */
/* http://harviacode.com */